travis:
  secure:
    BINSTAR_TOKEN: j35gqD/zTYs+czbh6syIuYt9zldj77OH1Op0SWH1PmILCoCdCdSNNSy+CPcDg6d/HMksBWfs483JKyq8Ezm7eo3abXksoQ9LHLp/1rS5KGnllWBXYIAnZYalK3/fuwme60ZDbovQWqaQFjy5xOIpcmBWr7oDY4V29KSI+0QoWdPXqbzTewP6fre5/tLU3IYeAOnsP5UrMdWtidnB5sha7VYzxWFH9x0mMPyr1iNEZzpBDaOmVFOUMFhANz0XdnQlNb+DrRweEgoIGQLMlF49l7JwLDrYtxHwXBbETJfEncip/fug4jSzCTrQfeeUqbfD4CBe+RoLcQxYf8nSPddPuoMlxwptHglGuPBBg+cSaLhyrwPIuIcDIMgPWWIZesK6FG2jqlivt8e7fBdl6kl0qQ3l9dwEEVJG1RPY58xyiaBTkPHXjBiBYxx94x1vVE8Civ1ySNddX6MBPw48+jeAieUyQRy9hCevT8xBg+OmHZt9lN68ZOzFX7OjmML53sC2+px/ASWxeUavAm7P5kpenGoc5r93akDlZn0ZhRB1Wuk1upZVLmukd3Zj0QwmlVykbhSxsz5zj4dQMUdevswfoHMusU1N3QxUzAawosevTP42GEYXia9EmTL+a7vo/gCPUksMyElQPn5hlehaHvfRcxQAa6UM8vsnkRhrSs6r7sA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
