travis:
  secure:
    BINSTAR_TOKEN: k5DzIGLypgTwoaPaYkq00Lp1h0W+ZZgQScbqHVjOXmvQAQteyAhPE1nZkdw6cvwYZV967XkXLvyEQytk0opxQuU9TxGc5ZhKRUVPm70siXwFMwtpKBh8f+sh48bQ/hO9s6k2M5EQ/FfyvzFPtOKz57PL206yGFatPXTcVlArzKr1ivkD3nQpCABgSv6mFM5vBsyjYgawyzRLWfQ4pBAQ25URi2cjzDK+5sZDWjuhoRaQPOxAGTX/ONyupW4xlKd3W9R5YiXReI2ZkZ1P9lgtdbNhlKHjfZ4//98DI4EBPFcNXEsg6lpln0kp08JfV0cCG2hUCYcNWHUuYSe+SavMY9KtGr+1MJmgngUhJ+B4qTCjPdzrfFccUC4RhkWylm+pv76RZc7lvbzdKZb8Rr4ckdTud+iaH7QNhZlvS4Kt5hD96xxUcGTMXYr1+/CWJGGmS2sVScCAe9dSw55XOYq702PQ2yPXNXEpm5NbUvLF+imU2NoTlL6/VAQn7sQ5bLsZ0VhNR3RZxTiqtvi9Qw8UPBosNiLW+btkpESFmG74n9Mq5yGRtTuMeaG30heQeJCGnaJLCr0cM3YKMwYfKX76Yxll68KqSSIOwSkfAq2ZspnSD7TUm89eo0MdHgN7VyHQhR+vGM2++93VX5L12dJ61ank0BnR6hREVfKe/8MnlJY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
